# -*- coding: utf-8 -*-
"""FreightWise

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16FOCBE4n3vmOdtJr1udC5kqn8NRwyRx8

# SIH26006 – Intelligent Freight Forecasting Model

## Project Objective

This project develops a machine-learning-based forecasting system for
freight-market conditions relevant to vessel chartering and bulk cargo
procurement for the East Coast of India.

The forecasting target is the BDRY closing value, used as a
dry-bulk freight-market proxy.

The primary forecasting horizon is t+14 future available observations.

The project includes:
- Dataset auditing
- Data cleaning
- Leakage-safe feature engineering
- Chronological train/validation/test splitting
- Machine-learning model comparison
- Extra Trees final ML model
- Walk-forward stability analysis
- Feature importance
- Future forecasting
- Deployment-ready prediction function

# 1. Project Setup

The required Python libraries are imported for data handling,
visualization, feature engineering, model training, and evaluation.
"""


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import time
import warnings
import joblib
from sklearn.model_selection import TimeSeriesSplit
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.linear_model import Ridge, Lasso
from sklearn.ensemble import (
    RandomForestRegressor,
    ExtraTreesRegressor,
    HistGradientBoostingRegressor
)

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error
)

from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor

"""# 2. Dataset Loading

The cleaned master dataset is loaded for analysis and forecasting.

The dataset contains historical freight-market information together
with related economic and industrial indicators.
"""

csv_path = "/content/master_training_dataset_clean.csv"
excel_path = "/content/Paradip_Master_Dataset_Clean.xlsx"

df = pd.read_csv(csv_path)

excel = pd.ExcelFile(excel_path)

print(df.shape)
print(excel.sheet_names)

"""# 3. Dataset Audit

Before building the forecasting model, the dataset is examined to
understand its structure, date coverage, data types, missing values,
duplicate records, and available variables.
"""

print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

"""## 3.1 Date and Time Coverage

The date column is converted into a proper datetime format and the
historical coverage and chronological ordering of the observations
are checked.
"""

df["date"] = pd.to_datetime(df["date"])

print("Start:", df["date"].min())
print("End:", df["date"].max())

print("\nUnique dates:", df["date"].nunique())

"""# 4. Target Definition

The forecasting target is the `bdry_close` variable.

It represents the closing value of the BDRY dry-bulk freight-market
instrument and is used here as a proxy for broader dry-bulk freight
market conditions.

It should not be interpreted as an exact route-specific vessel
charter rate for a particular East Coast port.
"""

TARGET = "bdry_close"

print(df[TARGET].describe())

"""## 4.1 Target Variable Visualization

The historical target series is visualized to understand its overall
movement and variation over time.
"""

plt.figure(figsize=(14,5))

plt.plot(df["date"], df[TARGET])

plt.title("BDRY Freight-Market Proxy")
plt.xlabel("date")
plt.ylabel("Freight-market proxy")

plt.grid(True)
plt.show()

"""# 5. Feature Engineering

Historical information is transformed into forecasting features.

The features include:
- Historical lag values
- Rolling statistics
- Returns
- Calendar features
- Previous-day market information
- Lagged external indicators

Only information available before the forecast point is used to
construct forecasting features.
"""

df = df.sort_values("date").reset_index(drop=True)
print(df["date"].is_monotonic_increasing)

"""## 5.1 Lag and Rolling Features

Lag features capture previous freight-market values, while rolling
statistics summarize recent historical behavior.

The rolling calculations are shifted so that the current target value
is not used as an input feature.
"""

HORIZON = 14
df["target"] = df[TARGET].shift(-HORIZON)
model_df = df.dropna(subset=["target"]).copy()

for lag in [1, 2, 3, 5, 7, 14, 21, 30]:
    model_df[f"close_lag_{lag}"] = model_df[TARGET].shift(lag)

model_df["roll_7_mean"] = (
    model_df[TARGET]
    .shift(1)
    .rolling(7)
    .mean()
)

model_df["roll_14_mean"] = (
    model_df[TARGET]
    .shift(1)
    .rolling(14)
    .mean()
)

model_df["roll_30_mean"] = (
    model_df[TARGET]
    .shift(1)
    .rolling(30)
    .mean()
)
model_df["roll_7_std"] = (
    model_df[TARGET]
    .shift(1)
    .rolling(7)
    .std()
)

model_df["roll_30_std"] = (
    model_df[TARGET]
    .shift(1)
    .rolling(30)
    .std()
)

model_df["return_1"] = (
    model_df[TARGET].shift(1) /
    model_df[TARGET].shift(2) - 1
)

model_df["return_7"] = (
    model_df[TARGET].shift(1) /
    model_df[TARGET].shift(8) - 1
)

"""## 5.2 Market and Calendar Features

Additional features are created from historical price changes,
daily market information, and calendar information such as day,
month, quarter, and year.
"""

model_df["day_of_week"] = model_df["date"].dt.dayofweek
model_df["month"] = model_df["date"].dt.month
model_df["quarter"] = model_df["date"].dt.quarter
model_df["year"] = model_df["date"].dt.year

"""## 5.3 External Indicator Features

Available economic and industrial indicators are incorporated as
additional predictors.

Their lagged values are used where required to ensure that future
information is not introduced into the model.
"""

model_df["range_lag_1"] = model_df["bdry_daily_range"].shift(1)

model_df["volume_lag_1"] = model_df["bdry_volume"].shift(1)

model_df["high_lag_1"] = model_df["bdry_high"].shift(1)

model_df["low_lag_1"] = model_df["bdry_low"].shift(1)

external_columns = [
    "COL.HRD.IMP.COK.DOC",
    "COL.HRD.IMP.STM.DOC",
    "COL.HRD.IMP.TOT.DOC",
    "COL.HRD.IMP.CIS",
    "COL.HRD.PRD.GrandTotal.MCL",
    "IDY.PRD.OEA.COL",
    "IDY.PRD.OEA.STL",
    "CEM.PRD",
    "ELY.DEM.POS.TOT.India"
]

for col in external_columns:
    model_df[col + "_lag1"] = model_df[col].shift(1)

model_df = model_df.dropna().reset_index(drop=True)
print(model_df.shape)

print(model_df.isnull().sum().sum())

"""# 6. Data Leakage Prevention

Data leakage occurs when information that would not have been known at
the forecasting time is used as a model input.

The feature set is therefore checked to ensure that target variables
and future-derived information are excluded from the predictors.
"""

print("Target:", TARGET)

print("\nTarget correlation with suspicious features:")

for col in model_df.columns:
    if col != "target" and "roll" in col.lower():
        print(col, model_df[col].corr(model_df["target"]))

"""# 7. Chronological Data Split

Because this is a time-series forecasting problem, the data is split
chronologically rather than randomly.

Earlier observations are used for training and later observations are
reserved for validation and testing.

This preserves the real-world forecasting sequence.
"""

n = len(model_df)

train_end = int(n * 0.70)
val_end = int(n * 0.85)

train = model_df.iloc[:train_end]
validation = model_df.iloc[train_end:val_end]
test = model_df.iloc[val_end:]
print(
    "Train:",
    train["date"].min(),
    "to",
    train["date"].max()
)

print(
    "Validation:",
    validation["date"].min(),
    "to",
    validation["date"].max()
)

print(
    "Test:",
    test["date"].min(),
    "to",
    test["date"].max()
)

def smape(y_true, y_pred):
    denominator = (
        np.abs(y_true) +
        np.abs(y_pred)
    )

    return np.mean(
        2 * np.abs(y_pred - y_true) /
        np.where(denominator == 0, 1, denominator)
    ) * 100

"""# 8. Evaluation Metrics

The forecasting models are evaluated using:

- MAE – Mean Absolute Error
- RMSE – Root Mean Squared Error
- MSE – Mean Squared Error
- sMAPE – Symmetric Mean Absolute Percentage Error

Lower values indicate smaller forecasting errors.
"""

def evaluate_model(name, y_true, y_pred):

    mae = mean_absolute_error(y_true, y_pred)

    mse = mean_squared_error(y_true, y_pred)

    rmse = np.sqrt(mse)

    smape_value = smape(y_true, y_pred)

    return {
        "Model": name,
        "MAE": mae,
        "RMSE": rmse,
        "MSE": mse,
        "sMAPE": smape_value
    }

"""# 9. Baseline Benchmark

Naive Persistence is used as a baseline benchmark.

It assumes that the future value can be estimated from the most recent
available value.

The benchmark provides a reference point for determining whether the
machine-learning models provide additional predictive value.
"""

def evaluate_model(name, y_true, y_pred):

    mae = mean_absolute_error(y_true, y_pred)

    mse = mean_squared_error(y_true, y_pred)

    rmse = np.sqrt(mse)

    smape_value = smape(y_true, y_pred)

    return {
        "Model": name,
        "MAE": mae,
        "RMSE": rmse,
        "MSE": mse,
        "sMAPE": smape_value
    }

import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error

# Actual values
actual = test["target"].values

# Naive prediction
naive_pred = test["bdry_close"].values

# Metrics
naive_mae = mean_absolute_error(actual, naive_pred)
naive_mse = mean_squared_error(actual, naive_pred)
naive_rmse = np.sqrt(naive_mse)

# sMAPE
naive_smape = np.mean(
    2 * np.abs(actual - naive_pred) /
    (np.abs(actual) + np.abs(naive_pred))
) * 100

print("Naive Baseline Results")
print("----------------------")
print("MAE  :", naive_mae)
print("RMSE :", naive_rmse)
print("MSE  :", naive_mse)
print("sMAPE:", naive_smape)

DROP_COLUMNS = [
    "date",
    "target",
    "bdry_close",
    "bdry_roll7_mean",
    "bdry_roll30_mean"
]

FEATURES = [
    c for c in model_df.columns
    if c not in DROP_COLUMNS
]

X_train = train[FEATURES]
y_train = train["target"]

X_val = validation[FEATURES]
y_val = validation["target"]

X_test = test[FEATURES]
y_test = test["target"]

print("bdry_roll7_mean" in FEATURES)
print("bdry_roll30_mean" in FEATURES)
print(len(FEATURES))

print(FEATURES)

# Final leakage-safe feature list

feature_cols = [
    "bdry_open",
    "bdry_high",
    "bdry_low",
    "bdry_close",
    "bdry_volume",
    "bdry_daily_range",
    "bdry_lag1",
    "bdry_lag7",
    "bdry_lag30",
    "bdry_roll7_mean",
    "bdry_roll30_mean",
    "COL.HRD.IMP.COK.DOC",
    "COL.HRD.IMP.STM.DOC",
    "COL.HRD.IMP.TOT.DOC",
    "COL.HRD.IMP.CIS",
    "COL.PRD.GrandTotal.MCL",
    "IDY.PRD.OEA.COL",
    "IDY.PRD.OEA.STL",
    "CEM.PRD",
    "ELY.DEM.POS.TOT.India",
    "close_lag_1",
    "close_lag_2",
    "close_lag_3",
    "close_lag_5",
    "close_lag_7",
    "close_lag_14",
    "close_lag_21",
    "close_lag_30",
    "roll_7_mean",
    "roll_14_mean",
    "roll_30_mean",
    "roll_7_std",
    "roll_30_std",
    "return_1",
    "return_7",
    "day_of_week",
    "month",
    "quarter",
    "year",
    "range_lag_1",
    "volume_lag_1",
    "high_lag_1",
    "low_lag_1",
    "COL.HRD.IMP.COK.DOC_lag1",
    "COL.HRD.IMP.STM.DOC_lag1",
    "COL.HRD.IMP.TOT.DOC_lag1",
    "COL.HRD.IMP.CIS_lag1",
    "COL.PRD.GrandTotal.MCL_lag1",
    "IDY.PRD.OEA.COL_lag1",
    "IDY.PRD.OEA.STL_lag1",
    "CEM.PRD_lag1",
    "ELY.DEM.POS.TOT.India_lag1"
]

# Check for target leakage
target_features = [
    col for col in FEATURES
    if col.startswith("target")
]

print("Number of model features:", len(FEATURES))
print("Target columns in features:", target_features)

if len(target_features) == 0:
    print("✅ No target columns present in model features.")
else:
    print("❌ Target leakage detected!")

# Final t+14 target
target_col = "target"

# Prepare training, validation and test data
X_train = train[FEATURES]
y_train = train[target_col]

X_val = validation[FEATURES]
y_val = validation[target_col]

X_test = test[FEATURES]
y_test = test[target_col]

print("Training shape:", X_train.shape)
print("Validation shape:", X_val.shape)
print("Test shape:", X_test.shape)

"""## 10. Final t+14 Forecasting Setup

The final forecasting task predicts the BDRY closing value 14 future
available observations ahead.

Multiple machine-learning regression models are evaluated using the
same leakage-safe feature set and chronological evaluation approach.
"""

import time
import numpy as np
import pandas as pd

from sklearn.linear_model import Lasso, Ridge
from sklearn.ensemble import (
    RandomForestRegressor,
    ExtraTreesRegressor,
    HistGradientBoostingRegressor
)
from sklearn.metrics import mean_absolute_error, mean_squared_error

from xgboost import XGBRegressor
from catboost import CatBoostRegressor


models = {
    "Lasso": Lasso(alpha=0.01, max_iter=10000),

    "Ridge": Ridge(alpha=1.0),

    "Random Forest": RandomForestRegressor(
        n_estimators=300,
        random_state=42,
        n_jobs=-1
    ),

    "Extra Trees": ExtraTreesRegressor(
        n_estimators=300,
        random_state=42,
        n_jobs=-1
    ),

    "HistGradientBoosting": HistGradientBoostingRegressor(
        max_iter=300,
        learning_rate=0.05,
        max_depth=6,
        random_state=42
    ),

    "XGBoost": XGBRegressor(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=6,
        random_state=42,
        n_jobs=-1,
        objective="reg:squarederror"
    ),

    "CatBoost": CatBoostRegressor(
        iterations=500,
        learning_rate=0.05,
        depth=6,
        loss_function="RMSE",
        random_seed=42,
        verbose=False
    )
}


results = []
trained_models = {}

for name, model in models.items():

    start_time = time.time()

    model.fit(X_train, y_train)

    predictions = model.predict(X_test)

    training_time = time.time() - start_time

    mae = mean_absolute_error(y_test, predictions)
    rmse = np.sqrt(mean_squared_error(y_test, predictions))
    mse = mean_squared_error(y_test, predictions)

    smape = np.mean(
        2 * np.abs(y_test.values - predictions) /
        (np.abs(y_test.values) + np.abs(predictions))
    ) * 100

    results.append({
        "Model": name,
        "MAE": mae,
        "RMSE": rmse,
        "MSE": mse,
        "sMAPE (%)": smape,
        "Training Time (sec)": training_time
    })

    trained_models[name] = model


comparison_df = pd.DataFrame(results)

comparison_df = comparison_df.sort_values(
    by="MAE",
    ascending=True
).reset_index(drop=True)

display(comparison_df)

print("Target column:", "target")
print("Train shape:", train.shape)
print("Validation shape:", validation.shape)
print("Test shape:", test.shape)

print("\nTarget range:")
print(train["target"].min(), train["target"].max())
print(test["target"].min(), test["target"].max())

print("Target column:", "target")
print("First 5 target values:")
print(train["target"].head())

print("\nLast 5 target values:")
print(train["target"].tail())

print("\nTest dates:")
print(test["date"].min())
print(test["date"].max())

print("Target shift check:")

print("Train first date:", train["date"].min())
print("Train last date:", train["date"].max())

print("Target first value:", train["target"].iloc[0])

print("\nOriginal close at train first date:")
print(train["bdry_close"].iloc[0] if "bdry_close" in train.columns else "bdry_close not in train")

"""### Walk-Forward Stability Check

The Extra Trees model is evaluated across multiple chronological
time blocks to examine whether its performance remains stable over
different market periods.

This helps identify whether the model's performance changes over time.
"""

from sklearn.ensemble import ExtraTreesRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np
import pandas as pd

final_temp = model_df.copy()

# Use the already prepared leakage-safe t+14 dataset
data = final_temp.copy()

target_col = "target"

# Make sure only non-target columns are used
final_temp = model_df.copy()

data = final_temp.copy()

target_col = "target"

X = data[FEATURES]
y = data[target_col]

# 4 chronological evaluation blocks
n = len(data)

train_end = int(n * 0.55)
block_size = int((n - train_end) / 4)

walk_results = []

for i in range(4):

    test_start = train_end + i * block_size

    if i < 3:
        test_end = train_end + (i + 1) * block_size
    else:
        test_end = n

    X_train_wf = X.iloc[:test_start]
    y_train_wf = y.iloc[:test_start]

    X_test_wf = X.iloc[test_start:test_end]
    y_test_wf = y.iloc[test_start:test_end]

    model = ExtraTreesRegressor(
        n_estimators=300,
        random_state=42,
        n_jobs=-1
    )

    model.fit(X_train_wf, y_train_wf)

    pred_wf = model.predict(X_test_wf)

    mae = mean_absolute_error(y_test_wf, pred_wf)
    rmse = np.sqrt(mean_squared_error(y_test_wf, pred_wf))

    smape = np.mean(
        2 * np.abs(y_test_wf.values - pred_wf) /
        (np.abs(y_test_wf.values) + np.abs(pred_wf))
    ) * 100

    walk_results.append({
        "Block": i + 1,
        "Start": data["date"].iloc[test_start],
        "End": data["date"].iloc[test_end - 1],
        "MAE": mae,
        "RMSE": rmse,
        "sMAPE (%)": smape
    })

walk_forward_df = pd.DataFrame(walk_results)

display(walk_forward_df)

"""## 11. Final Machine-Learning Model – Extra Trees

Extra Trees is selected as the final machine-learning model candidate
because it achieved the lowest MAE and sMAPE among the evaluated
machine-learning models for the t+14 forecasting task.

The final model is evaluated on the unseen chronological test period.
"""

# Final Extra Trees Model

final_et_model = ExtraTreesRegressor(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

final_et_model.fit(X_train, y_train)

final_et_pred = final_et_model.predict(X_test)

final_et_mae = mean_absolute_error(y_test, final_et_pred)
final_et_rmse = np.sqrt(mean_squared_error(y_test, final_et_pred))
final_et_mse = mean_squared_error(y_test, final_et_pred)

final_et_smape = np.mean(
    2 * np.abs(y_test.values - final_et_pred) /
    (np.abs(y_test.values) + np.abs(final_et_pred))
) * 100

print("FINAL ML MODEL: EXTRA TREES")
print("Forecast Horizon: t+14")
print(f"MAE: {final_et_mae:.4f}")
print(f"RMSE: {final_et_rmse:.4f}")
print(f"MSE: {final_et_mse:.4f}")
print(f"sMAPE: {final_et_smape:.2f}%")

"""## 12. Model Interpretability

Feature importance is examined to understand which input variables
contributed most to the Extra Trees model's predictions.

Feature importance indicates model reliance on variables and should not
be interpreted as proof of causation.
"""

# Final Extra Trees Feature Importance

et_feature_importance = pd.DataFrame({
    "Feature": FEATURES,
    "Importance": final_et_model.feature_importances_
})

et_feature_importance = et_feature_importance.sort_values(
    by="Importance",
    ascending=False
)

print("Top 15 Extra Trees Features:")
display(et_feature_importance.head(15))

"""### Top Feature Importance Visualization

The most influential features identified by the Extra Trees model are
visualized to make the model's inputs easier to interpret.
"""

plt.figure(figsize=(10, 6))

top_features = et_feature_importance.head(15).sort_values("Importance")

plt.barh(
    top_features["Feature"],
    top_features["Importance"]
)

plt.xlabel("Feature Importance")
plt.ylabel("Feature")
plt.title("Extra Trees Feature Importance — t+14 Forecast")
plt.grid(axis="x")
plt.show()

"""## 13. Prediction Analysis

### Actual vs Predicted Values

The actual and predicted values on the unseen test period are compared
visually to examine how well the model follows the observed freight
market movements.
"""

plt.figure(figsize=(12, 6))

plt.plot(y_test.values, label="Actual")
plt.plot(final_et_pred, label="Predicted")

plt.xlabel("Test Set Observation")
plt.ylabel("BDRY Close")
plt.title("Extra Trees — Actual vs Predicted (t+14)")
plt.legend()
plt.grid(True)

plt.show()

"""### Residual Analysis

Residuals are calculated as:

Residual = Actual Value − Predicted Value

The residual plot is used to identify periods with larger forecasting
errors and to check whether errors show noticeable patterns.
"""

residuals = y_test.values - final_et_pred

plt.figure(figsize=(12, 6))

plt.plot(residuals)

plt.axhline(0, linestyle="--")

plt.xlabel("Test Set Observation")
plt.ylabel("Residual (Actual - Predicted)")
plt.title("Extra Trees — Residuals (t+14)")
plt.grid(True)

plt.show()

"""### Test Prediction Results

The actual values, model predictions, and residuals are stored together
for further analysis and reproducibility.
"""

final_prediction_df = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": final_et_pred,
    "Residual": y_test.values - final_et_pred
})

display(final_prediction_df.head(10))

final_prediction_df.to_csv(
    "extra_trees_t14_test_predictions.csv",
    index=False
)

print("Saved: extra_trees_t14_test_predictions.csv")

"""## 14. Model Artifacts

The trained Extra Trees model is saved so that it can be reused later
without retraining the model.
"""

import joblib

joblib.dump(final_et_model, "extra_trees_t14_model.pkl")

print("Saved: extra_trees_t14_model.pkl")

"""The feature importance results are also saved for documentation,
interpretability, and future analysis.
"""

et_feature_importance.to_csv(
    "extra_trees_t14_feature_importance.csv",
    index=False
)

print("Saved: extra_trees_t14_feature_importance.csv")

"""## 15. Machine-Learning Model Comparison

The evaluated machine-learning models are compared using the same
unseen chronological t+14 test period.

The comparison uses MAE, RMSE, MSE, sMAPE, and training time.
Lower error values indicate smaller forecasting errors.
"""

model_results = pd.DataFrame({
    "Model": [
        "Extra Trees",
        "CatBoost",
        "Random Forest",
        "HistGradientBoosting",
        "XGBoost",
        "Lasso",
        "Ridge"
    ],
    "MAE": [
        0.962084,
        1.005419,
        1.149457,
        1.409418,
        1.498406,
        1.677041,
        1.728052
    ],
    "RMSE": [
        1.405560,
        1.329634,
        1.574889,
        1.802777,
        1.896580,
        2.133437,
        2.178144
    ],
    "MSE": [
        1.975598,
        1.767926,
        2.480276,
        3.250004,
        3.597016,
        4.551555,
        4.744313
    ],
    "sMAPE (%)": [
        8.781580,
        8.995527,
        10.699747,
        14.368631,
        13.849094,
        15.500227,
        15.941126
    ],
    "Training_Time_sec": [
        3.015888,
        2.727486,
        5.724981,
        0.502512,
        1.276471,
        0.332957,
        0.004128
    ]
})

display(model_results)

"""### Saving Model Comparison Results

The model comparison results are saved as a CSV file so that the
experimental results can be reproduced and used in the final report.
"""

model_results.to_csv(
    "model_comparison_t14.csv",
    index=False
)

print("✅ Model comparison saved.")

"""### Model Comparison Visualization

The MAE values of the evaluated machine-learning models are visualized
to provide a direct comparison of their forecasting errors.
"""

comparison_plot = model_results.sort_values("MAE")

plt.figure(figsize=(10, 6))

plt.barh(
    comparison_plot["Model"],
    comparison_plot["MAE"]
)

plt.xlabel("MAE")
plt.ylabel("Model")
plt.title("ML Model Comparison — t+14 Forecast")
plt.grid(axis="x")

plt.show()

"""## 16. Future Forecast Preparation

Before generating a future forecast, the latest available feature
information is identified from the prepared dataset.
"""

latest_features = final_temp[
    ["date"] + FEATURES
].dropna()

print("Latest available feature date:")
print(latest_features["date"].max())

display(latest_features.tail(3))

"""### Latest Available Dataset Information

The original cleaned dataset is loaded to verify the latest available
observation and the feature structure used by the final model.
"""

# Load the original cleaned dataset
import pandas as pd

raw_df = pd.read_csv("/content/master_training_dataset_clean.csv")

print("Original dataset shape:", raw_df.shape)

print("\nLatest dates in original dataset:")
display(raw_df[["date", "bdry_close"]].tail(10))

print("\nNumber of model features:", len(FEATURES))

print("\nFirst 20 model features:")
print(FEATURES[:20])

"""### Final Model Feature List

The final model uses 49 features. The feature names are displayed to verify the inputs expected by the trained model.
"""

print("Number of features:", len(FEATURES))

for i, feature in enumerate(FEATURES, start=1):
    print(i, feature)

"""### Constructing the Latest Forecasting Features

The latest available dataset is processed using the same feature
engineering logic used during model training.

Lagged values and rolling statistics are constructed using only
information available before the forecast origin, preventing future
information from entering the prediction.
"""

# ---------------------------------------------------------
# 1. Load original cleaned dataset
# ---------------------------------------------------------
df_future = pd.read_csv("/content/master_training_dataset_clean.csv")

df_future["date"] = pd.to_datetime(df_future["date"])
df_future = df_future.sort_values("date").reset_index(drop=True)

# ---------------------------------------------------------
# 2. Basic market features
# ---------------------------------------------------------
df_future["bdry_daily_range"] = (
    df_future["bdry_high"] - df_future["bdry_low"]
)

# ---------------------------------------------------------
# 3. Original BDRY lag features
# ---------------------------------------------------------
df_future["bdry_lag1"] = df_future["bdry_close"].shift(1)
df_future["bdry_lag7"] = df_future["bdry_close"].shift(7)
df_future["bdry_lag30"] = df_future["bdry_close"].shift(30)

# Leakage-safe rolling features:
# only information available BEFORE the current date
df_future["bdry_roll7_mean"] = (
    df_future["bdry_close"]
    .shift(1)
    .rolling(7)
    .mean()
)

df_future["bdry_roll30_mean"] = (
    df_future["bdry_close"]
    .shift(1)
    .rolling(30)
    .mean()
)

# ---------------------------------------------------------
# 4. Additional close lag features
# ---------------------------------------------------------
df_future["close_lag_1"] = df_future["bdry_close"].shift(1)
df_future["close_lag_2"] = df_future["bdry_close"].shift(2)
df_future["close_lag_3"] = df_future["bdry_close"].shift(3)
df_future["close_lag_5"] = df_future["bdry_close"].shift(5)
df_future["close_lag_7"] = df_future["bdry_close"].shift(7)
df_future["close_lag_14"] = df_future["bdry_close"].shift(14)
df_future["close_lag_21"] = df_future["bdry_close"].shift(21)
df_future["close_lag_30"] = df_future["bdry_close"].shift(30)

# ---------------------------------------------------------
# 5. Leakage-safe rolling statistics
# ---------------------------------------------------------
df_future["roll_7_mean"] = (
    df_future["bdry_close"]
    .shift(1)
    .rolling(7)
    .mean()
)

df_future["roll_14_mean"] = (
    df_future["bdry_close"]
    .shift(1)
    .rolling(14)
    .mean()
)

df_future["roll_30_mean"] = (
    df_future["bdry_close"]
    .shift(1)
    .rolling(30)
    .mean()
)

df_future["roll_7_std"] = (
    df_future["bdry_close"]
    .shift(1)
    .rolling(7)
    .std()
)

df_future["roll_30_std"] = (
    df_future["bdry_close"]
    .shift(1)
    .rolling(30)
    .std()
)

# ---------------------------------------------------------
# 6. Returns
# ---------------------------------------------------------
df_future["return_1"] = (
    df_future["bdry_close"].shift(1) /
    df_future["bdry_close"].shift(2) - 1
)

df_future["return_7"] = (
    df_future["bdry_close"].shift(1) /
    df_future["bdry_close"].shift(8) - 1
)

# ---------------------------------------------------------
# 7. Calendar features
# ---------------------------------------------------------
df_future["day_of_week"] = df_future["date"].dt.dayofweek
df_future["month"] = df_future["date"].dt.month
df_future["quarter"] = df_future["date"].dt.quarter
df_future["year"] = df_future["date"].dt.year

# ---------------------------------------------------------
# 8. Lagged market features
# ---------------------------------------------------------
df_future["range_lag_1"] = df_future["bdry_daily_range"].shift(1)
df_future["volume_lag_1"] = df_future["bdry_volume"].shift(1)
df_future["high_lag_1"] = df_future["bdry_high"].shift(1)
df_future["low_lag_1"] = df_future["bdry_low"].shift(1)

# ---------------------------------------------------------
# 9. Lagged external indicators
# ---------------------------------------------------------
external_cols = [
    "COL.HRD.IMP.COK.DOC",
    "COL.HRD.IMP.STM.DOC",
    "COL.HRD.IMP.TOT.DOC",
    "COL.HRD.IMP.CIS",
    "COL.HRD.PRD.GrandTotal.MCL",
    "IDY.PRD.OEA.COL",
    "IDY.PRD.OEA.STL",
    "CEM.PRD",
    "ELY.DEM.POS.TOT.India"
]

for col in external_cols:
    df_future[col + "_lag1"] = df_future[col].shift(1)

# ---------------------------------------------------------
# 10. Check that all 49 model features exist
# ---------------------------------------------------------
missing_features = [
    col for col in FEATURES
    if col not in df_future.columns
]

print("Missing model features:", missing_features)

if len(missing_features) > 0:
    raise ValueError("Some model features are missing.")

# ---------------------------------------------------------
# 11. Select the latest available feature row
# ---------------------------------------------------------
latest_feature_row = (
    df_future[["date"] + FEATURES]
    .dropna()
    .tail(1)
)

print("\nLatest feature date:")
print(latest_feature_row["date"].iloc[0])

print("\nLatest actual BDRY close:")
print(
    df_future.loc[
        df_future["date"] == latest_feature_row["date"].iloc[0],
        "bdry_close"
    ].iloc[0]
)

print("\nFeature row shape:", latest_feature_row[FEATURES].shape)

"""## 17. Future t+14 Forecast

After the final Extra Trees model has been evaluated, the latest
available observations are used to generate a future t+14 forecast.

The forecast represents the predicted BDRY freight-market proxy value
14 future available observations ahead.
"""

# ---------------------------------------------------------
# Generate future t+14 forecast
# ---------------------------------------------------------

# Use the exact same features that were used to train final_et_model
X_future = latest_feature_row[FEATURES]

# Generate forecast
future_prediction = final_et_model.predict(X_future)[0]

# Display result
print("FINAL FUTURE FORECAST")
print("Forecast from date:", latest_feature_row["date"].iloc[0])
print("Forecast horizon: t+14")
print("Forecasted BDRY value:", round(future_prediction, 4))

"""### Saving the Future Forecast

The forecast origin date, forecasting horizon, and predicted BDRY value
are saved for reporting and later use.
"""

future_forecast_df = pd.DataFrame({
    "Forecast_From_Date": [
        latest_feature_row["date"].iloc[0]
    ],
    "Horizon": ["t+14"],
    "Forecasted_BDRY": [future_prediction]
})

future_forecast_df.to_csv(
    "extra_trees_t14_future_forecast.csv",
    index=False
)

display(future_forecast_df)

print("✅ Future forecast saved.")

"""## 18. Reproducibility Artifacts

The final feature list is saved so that the same input structure can
be used when the model is deployed or reused.
"""

feature_list_df = pd.DataFrame({
    "Feature": FEATURES
})

feature_list_df.to_csv(
    "extra_trees_t14_feature_list.csv",
    index=False
)

print("✅ Feature list saved.")

"""### Final Model Summary

A compact summary of the final model, forecasting horizon, target,
evaluation metrics, and number of features is saved for documentation
and reporting.

### Final Feature Importance Graph

The final feature-importance visualization is saved as a high-resolution
image for use in the project report and presentation.
"""

final_summary = pd.DataFrame({
    "Item": [
        "Final ML Model",
        "Forecast Horizon",
        "Target",
        "MAE",
        "RMSE",
        "MSE",
        "sMAPE",
        "Number of Features"
    ],
    "Value": [
        "Extra Trees",
        "t+14",
        "BDRY Close",
        0.962084,
        1.405560,
        1.975598,
        "8.781580%",
        49
    ]
})

import matplotlib.pyplot as plt

top_features = et_feature_importance.head(15)

plt.figure(figsize=(10, 7))
plt.barh(
    top_features["Feature"][::-1],
    top_features["Importance"][::-1]
)

plt.xlabel("Importance")
plt.ylabel("Feature")
plt.title("Top 15 Extra Trees Feature Importances")
plt.tight_layout()

plt.savefig(
    "extra_trees_t14_feature_importance.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

"""## 19. Deployment-Ready Prediction Function

A prediction function is created so that the trained Extra Trees model
can receive a feature row and return a t+14 freight-market forecast.

The function uses the same feature ordering as the trained model.

### Testing the Prediction Function

The deployment-ready function is tested using the latest available
feature row to confirm that it produces the expected type of forecast.
"""

def predict_freight_t14(input_data):
    input_df = pd.DataFrame([input_data])

    # Use the exact features used during model training
    missing_features = [col for col in FEATURES if col not in input_df.columns]

    if missing_features:
        raise ValueError(f"Missing features: {missing_features}")

    input_df = input_df[FEATURES]

    return final_et_model.predict(input_df)[0]


# Use the current model features
latest_input = latest_feature_row[FEATURES].iloc[0].to_dict()

prediction = predict_freight_t14(latest_input)

print("Predicted BDRY:", round(prediction, 4))

"""# 20. Conclusion and Limitations

The final machine-learning model for the t+14 forecasting task is
Extra Trees. It achieved the lowest MAE and sMAPE among the evaluated
machine-learning models on the unseen test period.

However, Naive Persistence achieved lower overall test error than the
machine-learning models. Therefore, the results do not demonstrate
that machine learning consistently outperforms the baseline.

The BDRY closing value is a dry-bulk freight-market proxy rather than
an exact route-specific charter rate. Therefore, this forecasting
system should be interpreted as a freight-market forecasting component
that can support vessel chartering and bulk cargo procurement analysis,
rather than as a direct quotation of vessel charter rates.

Future work can incorporate longer-term route-specific charter-rate
data, additional port-level historical observations, vessel movement
data, and richer operational information when such data becomes
available.
"""